
import {
  Icon,
  Search,
  Loading,
  Button,
  Rate,
  Image as VanImage,
  Lazyload,
  // Toast,
  // Form,
  // Field,
  // CellGroup,
  // Cell,
  // Tab,
  // Tabs,
  // Calendar,
  // List,
  // Popup,
  // NavBar,
  // PullRefresh,
  // Picker,
  // Divider,
  // Sticky,
  // DatetimePicker,
  // ActionSheet,
  // Area,
  // Popover,
  // Cascader,
  // Tabbar,
  // TabbarItem,
  // Collapse,
  // CollapseItem,
  // Checkbox,
  // CheckboxGroup,
  // DropdownMenu,
  // DropdownItem,
  // Overlay,
  // Switch,
} from "vant";

const components = [
  Icon,
  Search,
  Loading,
  Button,
  Rate,
  VanImage,
  Lazyload,
  // Toast,
  // Form,
  // Field,
  // CellGroup,
  // Cell,
  // Tab,
  // Tabs,
  // Calendar,
  // List,
  // Popup,
  // NavBar,
  // PullRefresh,
  // Picker,
  // Divider,
  // Sticky,
  // DatetimePicker,
  // ActionSheet,
  // Area,
  // Popover,
  // Cascader,
  // Tabbar,
  // TabbarItem,
  // Collapse,
  // CollapseItem,
  // Checkbox,
  // CheckboxGroup,
  // DropdownMenu,
  // DropdownItem,
  // Overlay,
  // Switch,
];

export const vantPlugins = {
  // 注册组件
  install: (app: any) => {
    components.forEach((component: any) => app.component(component.name, component));
  },
};
